### ISSUE TITLE
Add SEO to homepage

### ISSUE THREAD

**Issue by undefine07** [waterfallphilippines/waterfallphilippines.github.io#10]
Keywords:
4/1/2020
1/4/2020
April Fools day 2020
Waterfall 2006

**Comment by Radriff** [comment]
Uhm so yeah we're looking at management to approve this but we're still early (7th meeting atm) still so probably we'll get going around October or November

**Comment by Radriff** [comment]
<meta name=”description” content=”Waterfall Philippines Official Website!”> 
<meta name=”robots” content=”noindex, nofollow” />
<meta name=”keywords” content=”4/1/2020, 1/4/2020, April Fools day 2020, Waterfall 2006”>
