### ISSUE TITLE
Add easter eggs!

### ISSUE THREAD

**Issue by Radriff** [waterfallphilippines/waterfallphilippines.github.io#9]
Describe your easter eggs here!

**Comment by Radriff** [comment]
*Route to waterfall flash game upon clicking the image
*Weird message box when hovering somewhere near the counter (rightmost side)
*"Hello there" message hidden in the black screen version of the page (visible with other background colors or if page select all is done)

**Comment by undefine07** [comment]
Close to black color link to the agile manifesto at the bottom right?
